// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zbwgwezckpyelqaaozbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpid2d3ZXpja3B5ZWxxYWFvemJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzE3NTUsImV4cCI6MjA2MTU0Nzc1NX0.FFotjfcatop_gITA5InfkBG70rfwcg_7OKBNuVVg9dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
